/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboardStats {
  'pendingCrops' : bigint,
  'blockedUsers' : bigint,
  'totalOrders' : bigint,
  'approvedCrops' : bigint,
  'totalCrops' : bigint,
  'completedOrders' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : number,
  'totalBusinessUsers' : bigint,
  'totalFarmers' : bigint,
}
export interface AdminReport {
  'topCrops' : Array<
    { 'totalOrders' : bigint, 'cropName' : string, 'totalRevenue' : number }
  >,
  'recentOrders' : Array<Order>,
  'newUsersThisMonth' : bigint,
}
export interface BusinessDashboardStats {
  'pendingOrders' : bigint,
  'totalSpent' : number,
  'completedOrders' : bigint,
  'totalOrdersPlaced' : bigint,
}
export interface ChatMessage {
  'id' : MessageId,
  'isRead' : boolean,
  'receiverId' : UserId,
  'message' : string,
  'timestamp' : Timestamp,
  'senderId' : UserId,
}
export interface ConversationSummary {
  'partnerName' : string,
  'lastMessage' : string,
  'partnerId' : UserId,
  'unreadCount' : bigint,
  'lastTimestamp' : Timestamp,
}
export interface Crop {
  'id' : CropId,
  'status' : CropStatus,
  'farmerId' : UserId,
  'createdAt' : Timestamp,
  'unit' : string,
  'description' : string,
  'pricePerUnit' : number,
  'updatedAt' : Timestamp,
  'quantity' : number,
  'cropName' : string,
  'image' : [] | [ExternalBlob],
  'location' : string,
}
export type CropId = bigint;
export interface CropInput {
  'unit' : string,
  'description' : string,
  'pricePerUnit' : number,
  'quantity' : number,
  'cropName' : string,
  'image' : [] | [ExternalBlob],
  'location' : string,
}
export type CropStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface FarmerDashboardStats {
  'acceptedOrders' : bigint,
  'pendingCrops' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'approvedCrops' : bigint,
  'totalCrops' : bigint,
  'totalRevenue' : number,
}
export type MessageId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'farmerId' : UserId,
  'createdAt' : Timestamp,
  'cropId' : CropId,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'quantity' : number,
  'totalPrice' : number,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'isBlocked' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'mobile' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'business' : null } |
  { 'farmer' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCrop' : ActorMethod<[CropInput], Crop>,
  'approveCrop' : ActorMethod<[CropId], boolean>,
  'blockUser' : ActorMethod<[UserId], boolean>,
  'deleteCrop' : ActorMethod<[CropId], boolean>,
  'getAdminDashboardStats' : ActorMethod<[], AdminDashboardStats>,
  'getAdminReports' : ActorMethod<[], AdminReport>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBusinessDashboardStats' : ActorMethod<[], BusinessDashboardStats>,
  'getConversation' : ActorMethod<[UserId], Array<ChatMessage>>,
  'getCropById' : ActorMethod<[CropId], [] | [Crop]>,
  'getCrops' : ActorMethod<[[] | [CropStatus], [] | [UserId]], Array<Crop>>,
  'getFarmerDashboardStats' : ActorMethod<[], FarmerDashboardStats>,
  'getMyConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getMyCrops' : ActorMethod<[], Array<Crop>>,
  'getMyOrdersAsBuyer' : ActorMethod<[], Array<Order>>,
  'getMyOrdersAsFarmer' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getUsers' : ActorMethod<[], Array<UserProfile>>,
  'markMessagesRead' : ActorMethod<[UserId], undefined>,
  'placeOrder' : ActorMethod<[CropId, number], Order>,
  'registerUser' : ActorMethod<
    [string, string, string, UserRole, string],
    boolean
  >,
  'rejectCrop' : ActorMethod<[CropId], boolean>,
  'sendMessage' : ActorMethod<[UserId, string], ChatMessage>,
  'unblockUser' : ActorMethod<[UserId], boolean>,
  'updateCrop' : ActorMethod<[CropId, CropInput], boolean>,
  'updateMyProfile' : ActorMethod<[string, string, string], boolean>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];