/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CropInput = IDL.Record({
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'quantity' : IDL.Float64,
  'cropName' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const CropId = IDL.Nat;
export const CropStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Crop = IDL.Record({
  'id' : CropId,
  'status' : CropStatus,
  'farmerId' : UserId,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'updatedAt' : Timestamp,
  'quantity' : IDL.Float64,
  'cropName' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const AdminDashboardStats = IDL.Record({
  'pendingCrops' : IDL.Nat,
  'blockedUsers' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'approvedCrops' : IDL.Nat,
  'totalCrops' : IDL.Nat,
  'completedOrders' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'totalBusinessUsers' : IDL.Nat,
  'totalFarmers' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'farmerId' : UserId,
  'createdAt' : Timestamp,
  'cropId' : CropId,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'quantity' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const AdminReport = IDL.Record({
  'topCrops' : IDL.Vec(
    IDL.Record({
      'totalOrders' : IDL.Nat,
      'cropName' : IDL.Text,
      'totalRevenue' : IDL.Float64,
    })
  ),
  'recentOrders' : IDL.Vec(Order),
  'newUsersThisMonth' : IDL.Nat,
});
export const BusinessDashboardStats = IDL.Record({
  'pendingOrders' : IDL.Nat,
  'totalSpent' : IDL.Float64,
  'completedOrders' : IDL.Nat,
  'totalOrdersPlaced' : IDL.Nat,
});
export const MessageId = IDL.Nat;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'isRead' : IDL.Bool,
  'receiverId' : UserId,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'senderId' : UserId,
});
export const FarmerDashboardStats = IDL.Record({
  'acceptedOrders' : IDL.Nat,
  'pendingCrops' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'approvedCrops' : IDL.Nat,
  'totalCrops' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const ConversationSummary = IDL.Record({
  'partnerName' : IDL.Text,
  'lastMessage' : IDL.Text,
  'partnerId' : UserId,
  'unreadCount' : IDL.Nat,
  'lastTimestamp' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'business' : IDL.Null,
  'farmer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCrop' : IDL.Func([CropInput], [Crop], []),
  'approveCrop' : IDL.Func([CropId], [IDL.Bool], []),
  'blockUser' : IDL.Func([UserId], [IDL.Bool], []),
  'deleteCrop' : IDL.Func([CropId], [IDL.Bool], []),
  'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
  'getAdminReports' : IDL.Func([], [AdminReport], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBusinessDashboardStats' : IDL.Func(
      [],
      [BusinessDashboardStats],
      ['query'],
    ),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(ChatMessage)], ['query']),
  'getCropById' : IDL.Func([CropId], [IDL.Opt(Crop)], ['query']),
  'getCrops' : IDL.Func(
      [IDL.Opt(CropStatus), IDL.Opt(UserId)],
      [IDL.Vec(Crop)],
      ['query'],
    ),
  'getFarmerDashboardStats' : IDL.Func([], [FarmerDashboardStats], ['query']),
  'getMyConversations' : IDL.Func(
      [],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getMyCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getMyOrdersAsBuyer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyOrdersAsFarmer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markMessagesRead' : IDL.Func([UserId], [], []),
  'placeOrder' : IDL.Func([CropId, IDL.Float64], [Order], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'rejectCrop' : IDL.Func([CropId], [IDL.Bool], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [ChatMessage], []),
  'unblockUser' : IDL.Func([UserId], [IDL.Bool], []),
  'updateCrop' : IDL.Func([CropId, CropInput], [IDL.Bool], []),
  'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CropInput = IDL.Record({
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'quantity' : IDL.Float64,
    'cropName' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const CropId = IDL.Nat;
  const CropStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Crop = IDL.Record({
    'id' : CropId,
    'status' : CropStatus,
    'farmerId' : UserId,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'updatedAt' : Timestamp,
    'quantity' : IDL.Float64,
    'cropName' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const AdminDashboardStats = IDL.Record({
    'pendingCrops' : IDL.Nat,
    'blockedUsers' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'approvedCrops' : IDL.Nat,
    'totalCrops' : IDL.Nat,
    'completedOrders' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'totalBusinessUsers' : IDL.Nat,
    'totalFarmers' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'farmerId' : UserId,
    'createdAt' : Timestamp,
    'cropId' : CropId,
    'updatedAt' : Timestamp,
    'buyerId' : UserId,
    'quantity' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const AdminReport = IDL.Record({
    'topCrops' : IDL.Vec(
      IDL.Record({
        'totalOrders' : IDL.Nat,
        'cropName' : IDL.Text,
        'totalRevenue' : IDL.Float64,
      })
    ),
    'recentOrders' : IDL.Vec(Order),
    'newUsersThisMonth' : IDL.Nat,
  });
  const BusinessDashboardStats = IDL.Record({
    'pendingOrders' : IDL.Nat,
    'totalSpent' : IDL.Float64,
    'completedOrders' : IDL.Nat,
    'totalOrdersPlaced' : IDL.Nat,
  });
  const MessageId = IDL.Nat;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'isRead' : IDL.Bool,
    'receiverId' : UserId,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'senderId' : UserId,
  });
  const FarmerDashboardStats = IDL.Record({
    'acceptedOrders' : IDL.Nat,
    'pendingCrops' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'approvedCrops' : IDL.Nat,
    'totalCrops' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const ConversationSummary = IDL.Record({
    'partnerName' : IDL.Text,
    'lastMessage' : IDL.Text,
    'partnerId' : UserId,
    'unreadCount' : IDL.Nat,
    'lastTimestamp' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'business' : IDL.Null,
    'farmer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCrop' : IDL.Func([CropInput], [Crop], []),
    'approveCrop' : IDL.Func([CropId], [IDL.Bool], []),
    'blockUser' : IDL.Func([UserId], [IDL.Bool], []),
    'deleteCrop' : IDL.Func([CropId], [IDL.Bool], []),
    'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
    'getAdminReports' : IDL.Func([], [AdminReport], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBusinessDashboardStats' : IDL.Func(
        [],
        [BusinessDashboardStats],
        ['query'],
      ),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(ChatMessage)], ['query']),
    'getCropById' : IDL.Func([CropId], [IDL.Opt(Crop)], ['query']),
    'getCrops' : IDL.Func(
        [IDL.Opt(CropStatus), IDL.Opt(UserId)],
        [IDL.Vec(Crop)],
        ['query'],
      ),
    'getFarmerDashboardStats' : IDL.Func([], [FarmerDashboardStats], ['query']),
    'getMyConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getMyCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getMyOrdersAsBuyer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyOrdersAsFarmer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markMessagesRead' : IDL.Func([UserId], [], []),
    'placeOrder' : IDL.Func([CropId, IDL.Float64], [Order], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'rejectCrop' : IDL.Func([CropId], [IDL.Bool], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [ChatMessage], []),
    'unblockUser' : IDL.Func([UserId], [IDL.Bool], []),
    'updateCrop' : IDL.Func([CropId, CropInput], [IDL.Bool], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };