/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminReport {
    topCrops: Array<{
        totalOrders: bigint;
        cropName: string;
        totalRevenue: number;
    }>;
    recentOrders: Array<Order>;
    newUsersThisMonth: bigint;
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FarmerDashboardStats {
    acceptedOrders: bigint;
    pendingCrops: bigint;
    totalOrders: bigint;
    pendingOrders: bigint;
    approvedCrops: bigint;
    totalCrops: bigint;
    totalRevenue: number;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Crop {
    id: CropId;
    status: CropStatus;
    farmerId: UserId;
    createdAt: Timestamp;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt: Timestamp;
    quantity: number;
    cropName: string;
    image?: ExternalBlob;
    location: string;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    farmerId: UserId;
    createdAt: Timestamp;
    cropId: CropId;
    updatedAt: Timestamp;
    buyerId: UserId;
    quantity: number;
    totalPrice: number;
}
export interface BusinessDashboardStats {
    pendingOrders: bigint;
    totalSpent: number;
    completedOrders: bigint;
    totalOrdersPlaced: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AdminDashboardStats {
    pendingCrops: bigint;
    blockedUsers: bigint;
    totalOrders: bigint;
    approvedCrops: bigint;
    totalCrops: bigint;
    completedOrders: bigint;
    totalUsers: bigint;
    totalRevenue: number;
    totalBusinessUsers: bigint;
    totalFarmers: bigint;
}
export type UserId = Principal;
export type MessageId = bigint;
export type CropId = bigint;
export interface CropInput {
    unit: string;
    description: string;
    pricePerUnit: number;
    quantity: number;
    cropName: string;
    image?: ExternalBlob;
    location: string;
}
export interface ChatMessage {
    id: MessageId;
    isRead: boolean;
    receiverId: UserId;
    message: string;
    timestamp: Timestamp;
    senderId: UserId;
}
export interface ConversationSummary {
    partnerName: string;
    lastMessage: string;
    partnerId: UserId;
    unreadCount: bigint;
    lastTimestamp: Timestamp;
}
export type OrderId = bigint;
export interface UserProfile {
    id: UserId;
    isBlocked: boolean;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    mobile: string;
    location: string;
}
export enum CropStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    business = "business",
    farmer = "farmer"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addCrop(input: CropInput): Promise<Crop>;
    approveCrop(cropId: CropId): Promise<boolean>;
    blockUser(targetId: UserId): Promise<boolean>;
    deleteCrop(cropId: CropId): Promise<boolean>;
    getAdminDashboardStats(): Promise<AdminDashboardStats>;
    getAdminReports(): Promise<AdminReport>;
    getAllOrders(): Promise<Array<Order>>;
    getBusinessDashboardStats(): Promise<BusinessDashboardStats>;
    getConversation(partnerId: UserId): Promise<Array<ChatMessage>>;
    getCropById(cropId: CropId): Promise<Crop | null>;
    getCrops(statusFilter: CropStatus | null, farmerFilter: UserId | null): Promise<Array<Crop>>;
    getFarmerDashboardStats(): Promise<FarmerDashboardStats>;
    getMyConversations(): Promise<Array<ConversationSummary>>;
    getMyCrops(): Promise<Array<Crop>>;
    getMyOrdersAsBuyer(): Promise<Array<Order>>;
    getMyOrdersAsFarmer(): Promise<Array<Order>>;
    getMyProfile(): Promise<UserProfile | null>;
    getOrderById(orderId: OrderId): Promise<Order | null>;
    getUsers(): Promise<Array<UserProfile>>;
    markMessagesRead(senderId: UserId): Promise<void>;
    placeOrder(cropId: CropId, quantity: number): Promise<Order>;
    registerUser(name: string, email: string, mobile: string, role: UserRole, location: string): Promise<boolean>;
    rejectCrop(cropId: CropId): Promise<boolean>;
    sendMessage(receiverId: UserId, message: string): Promise<ChatMessage>;
    unblockUser(targetId: UserId): Promise<boolean>;
    updateCrop(cropId: CropId, input: CropInput): Promise<boolean>;
    updateMyProfile(name: string, mobile: string, location: string): Promise<boolean>;
    updateOrderStatus(orderId: OrderId, newStatus: OrderStatus): Promise<boolean>;
}
import type { AdminReport as _AdminReport, Crop as _Crop, CropId as _CropId, CropInput as _CropInput, CropStatus as _CropStatus, ExternalBlob as _ExternalBlob, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCrop(arg0: CropInput): Promise<Crop> {
        if (this.processError) {
            try {
                const result = await this.actor.addCrop(await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Crop_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCrop(await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Crop_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveCrop(arg0: CropId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCrop(arg0);
            return result;
        }
    }
    async blockUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async deleteCrop(arg0: CropId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCrop(arg0);
            return result;
        }
    }
    async getAdminDashboardStats(): Promise<AdminDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAdminReports(): Promise<AdminReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminReports();
                return from_candid_AdminReport_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminReports();
            return from_candid_AdminReport_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessDashboardStats(): Promise<BusinessDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessDashboardStats();
            return result;
        }
    }
    async getConversation(arg0: UserId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getCropById(arg0: CropId): Promise<Crop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrops(arg0: CropStatus | null, arg1: UserId | null): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrops(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrops(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerDashboardStats(): Promise<FarmerDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerDashboardStats();
            return result;
        }
    }
    async getMyConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConversations();
            return result;
        }
    }
    async getMyCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCrops();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCrops();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrdersAsBuyer(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrdersAsBuyer();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrdersAsBuyer();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrdersAsFarmer(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrdersAsFarmer();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrdersAsFarmer();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMessagesRead(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async placeOrder(arg0: CropId, arg1: number): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1);
                return from_candid_Order_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1);
            return from_candid_Order_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: UserRole, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_UserRole_n37(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_UserRole_n37(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async rejectCrop(arg0: CropId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCrop(arg0);
            return result;
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async unblockUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateCrop(arg0: CropId, arg1: CropInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCrop(arg0, await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCrop(arg0, await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminReport_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminReport): AdminReport {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CropStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropStatus): CropStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_Crop_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crop): Promise<Crop> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Crop]): Promise<Crop | null> {
    return value.length === 0 ? null : await from_candid_Crop_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CropId;
    status: _CropStatus;
    farmerId: _UserId;
    createdAt: _Timestamp;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt: _Timestamp;
    quantity: number;
    cropName: string;
    image: [] | [_ExternalBlob];
    location: string;
}): Promise<{
    id: CropId;
    status: CropStatus;
    farmerId: UserId;
    createdAt: Timestamp;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt: Timestamp;
    quantity: number;
    cropName: string;
    image?: ExternalBlob;
    location: string;
}> {
    return {
        id: value.id,
        status: from_candid_CropStatus_n13(_uploadFile, _downloadFile, value.status),
        farmerId: value.farmerId,
        createdAt: value.createdAt,
        unit: value.unit,
        description: value.description,
        pricePerUnit: value.pricePerUnit,
        updatedAt: value.updatedAt,
        quantity: value.quantity,
        cropName: value.cropName,
        image: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.image)),
        location: value.location
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topCrops: Array<{
        totalOrders: bigint;
        cropName: string;
        totalRevenue: number;
    }>;
    recentOrders: Array<_Order>;
    newUsersThisMonth: bigint;
}): {
    topCrops: Array<{
        totalOrders: bigint;
        cropName: string;
        totalRevenue: number;
    }>;
    recentOrders: Array<Order>;
    newUsersThisMonth: bigint;
} {
    return {
        topCrops: value.topCrops,
        recentOrders: from_candid_vec_n19(_uploadFile, _downloadFile, value.recentOrders),
        newUsersThisMonth: value.newUsersThisMonth
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    farmerId: _UserId;
    createdAt: _Timestamp;
    cropId: _CropId;
    updatedAt: _Timestamp;
    buyerId: _UserId;
    quantity: number;
    totalPrice: number;
}): {
    id: OrderId;
    status: OrderStatus;
    farmerId: UserId;
    createdAt: Timestamp;
    cropId: CropId;
    updatedAt: Timestamp;
    buyerId: UserId;
    quantity: number;
    totalPrice: number;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n22(_uploadFile, _downloadFile, value.status),
        farmerId: value.farmerId,
        createdAt: value.createdAt,
        cropId: value.cropId,
        updatedAt: value.updatedAt,
        buyerId: value.buyerId,
        quantity: value.quantity,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    isBlocked: boolean;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    mobile: string;
    location: string;
}): {
    id: UserId;
    isBlocked: boolean;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    mobile: string;
    location: string;
} {
    return {
        id: value.id,
        isBlocked: value.isBlocked,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n33(_uploadFile, _downloadFile, value.role),
        email: value.email,
        mobile: value.mobile,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CropStatus {
    return "pending" in value ? CropStatus.pending : "approved" in value ? CropStatus.approved : "rejected" in value ? CropStatus.rejected : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "rejected" in value ? OrderStatus.rejected : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    business: null;
} | {
    farmer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "business" in value ? UserRole.business : "farmer" in value ? UserRole.farmer : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Crop>): Promise<Array<Crop>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Crop_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n31(_uploadFile, _downloadFile, x));
}
async function to_candid_CropInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropInput): Promise<_CropInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CropStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropStatus): _CropStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropStatus | null): [] | [_CropStatus] {
    return value === null ? candid_none() : candid_some(to_candid_CropStatus_n26(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unit: string;
    description: string;
    pricePerUnit: number;
    quantity: number;
    cropName: string;
    image?: ExternalBlob;
    location: string;
}): Promise<{
    unit: string;
    description: string;
    pricePerUnit: number;
    quantity: number;
    cropName: string;
    image: [] | [_ExternalBlob];
    location: string;
}> {
    return {
        unit: value.unit,
        description: value.description,
        pricePerUnit: value.pricePerUnit,
        quantity: value.quantity,
        cropName: value.cropName,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)) : candid_none(),
        location: value.location
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == CropStatus.pending ? {
        pending: null
    } : value == CropStatus.approved ? {
        approved: null
    } : value == CropStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    business: null;
} | {
    farmer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.business ? {
        business: null
    } : value == UserRole.farmer ? {
        farmer: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.rejected ? {
        rejected: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
